name: Build and Test

on:
    push:
    pull_request:
        branches: [main]

jobs:
    build-windows:
        name: Build on Windows
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup MinGW
              uses: msys2/setup-msys2@v2
              with:
                  msystem: MINGW64
                  update: true
                  install: >-
                      mingw-w64-x86_64-gcc
                      mingw-w64-x86_64-make
                      make

            - name: Verify FreeGLUT files
              shell: pwsh
              run: |
                  Write-Host "Checking FreeGLUT files..."
                  if (Test-Path "lib/x64/freeglut.lib") {
                    Write-Host "✓ freeglut.lib found"
                  } else {
                    Write-Host "✗ freeglut.lib not found"
                    exit 1
                  }
                  if (Test-Path "bin/x64/freeglut.dll") {
                    Write-Host "✓ freeglut.dll found"
                  } else {
                    Write-Host "✗ freeglut.dll not found"
                    exit 1
                  }
                  if (Test-Path "include/GL/glut.h") {
                    Write-Host "✓ glut.h found"
                  } else {
                    Write-Host "✗ glut.h not found"
                    exit 1
                  }

            - name: Build project
              shell: msys2 {0}
              run: |
                  echo "Building Hoppy project..."
                  make clean
                  make

            - name: Check build artifacts
              shell: pwsh
              run: |
                  Write-Host "Checking build artifacts..."
                  if (Test-Path "bin/Hoppy.exe") {
                    Write-Host "✓ Hoppy.exe built successfully"
                    $size = (Get-Item "bin/Hoppy.exe").Length
                    Write-Host "  Executable size: $($size) bytes"
                  } else {
                    Write-Host "✗ Hoppy.exe not found - build failed"
                    exit 1
                  }

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: hoppy-windows-build
                  path: |
                      bin/Hoppy.exe
                      bin/freeglut.dll
                  retention-days: 7

            - name: Build summary
              shell: pwsh
              run: |
                  Write-Host "================================================"
                  Write-Host "Build Summary"
                  Write-Host "================================================"
                  Write-Host "Status: SUCCESS ✓"
                  Write-Host "Platform: Windows (MinGW64)"
                  Write-Host "Compiler: g++"
                  Write-Host "Build System: Make"
                  Write-Host "================================================"

    build-status:
        name: Build Status Check
        runs-on: ubuntu-latest
        needs: build-windows
        if: always()

        steps:
            - name: Check build status
              run: |
                  if [ "${{ needs.build-windows.result }}" == "success" ]; then
                    echo "✓ All builds passed successfully!"
                    exit 0
                  else
                    echo "✗ Build failed!"
                    exit 1
                  fi
